"use client";

import { useEffect, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { Loader2, AlertTriangle, FileCheck2, Sparkles } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import { archiveMatter, getArchivePrepData } from "@/server/archive/actions";
import { CLOSED_REASON_CN } from "@/server/archive/schemas";
import type { ArchiveChecklist } from "@/lib/archive/checklists";
import type { ArchiveClosedReason } from "@prisma/client";

interface Props {
  matterId: string;
  open: boolean;
  onOpenChange: (v: boolean) => void;
}

export function ArchiveWizardDialog({ matterId, open, onOpenChange }: Props) {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [checklist, setChecklist] = useState<ArchiveChecklist | null>(null);
  const [checked, setChecked] = useState<Record<string, boolean>>({});
  const [closedReason, setClosedReason] = useState<ArchiveClosedReason>("JUDGMENT");
  const [completedAt, setCompletedAt] = useState<string>(new Date().toISOString().slice(0, 10));
  const [judgmentSummary, setJudgmentSummary] = useState("");
  const [summary, setSummary] = useState("");
  const [summaryFromClose, setSummaryFromClose] = useState(false);
  const [forceWithMissing, setForceWithMissing] = useState(false);
  const [isPending, startTransition] = useTransition();

  useEffect(() => {
    if (!open) return;
    setLoading(true);
    setSummaryFromClose(false);
    getArchivePrepData(matterId)
      .then((data) => {
        setChecklist(data.checklist);
        // 默认所有 autoGenerated 项标 true（封皮/目录自动生成）
        const initial: Record<string, boolean> = {};
        for (const item of data.checklist.items) {
          if (item.autoGenerated) initial[item.id] = true;
        }
        setChecked(initial);
        if (data.matter.closedAt) {
          setCompletedAt(data.matter.closedAt.toISOString().slice(0, 10));
        }
        // v0.11: 引用结案时已写过的小结，可编辑覆盖
        if (data.existingSummary) {
          setSummary(data.existingSummary);
          setSummaryFromClose(true);
        }
      })
      .catch((err) => {
        toast.error("加载归档数据失败", { description: err instanceof Error ? err.message : "" });
        onOpenChange(false);
      })
      .finally(() => setLoading(false));
  }, [open, matterId, onOpenChange]);

  const missingRequired = checklist
    ? checklist.items.filter((i) => !i.autoGenerated && i.required && !checked[i.id])
    : [];

  function handleSubmit() {
    if (!summary.trim()) {
      toast.warning("请填写结案小结");
      return;
    }
    if (missingRequired.length > 0 && !forceWithMissing) {
      toast.warning(`仍有 ${missingRequired.length} 项必交材料未勾选`, {
        description: "如确实无法补齐，请勾选下方的'强制归档（缺项记录在档）'"
      });
      return;
    }
    startTransition(async () => {
      try {
        const result = await archiveMatter({
          matterId,
          summary,
          closedReason,
          completedAt: new Date(completedAt),
          judgmentSummary,
          checklist: checked,
          forceWithMissing
        });
        toast.success(`案件已归档（${result.archiveNo}）`, {
          description: "卷宗封皮 + 目录已自动生成至归档卷宗"
        });
        onOpenChange(false);
        router.refresh();
      } catch (err) {
        toast.error("归档失败", { description: err instanceof Error ? err.message : "" });
      }
    });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-3xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileCheck2 className="h-5 w-5 text-[#9B7BF7]" />
            归档案件
          </DialogTitle>
          <DialogDescription>
            归档不可逆。提交后案件转为只读，自动生成卷宗封皮和卷宗目录入归档卷宗。
          </DialogDescription>
        </DialogHeader>

        {loading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        ) : (
          <ScrollArea className="max-h-[60vh] pr-4">
            <div className="space-y-5">
              {/* 结案信息 */}
              <section className="space-y-3">
                <h3 className="text-sm font-medium">结案信息</h3>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1.5">
                    <Label className="text-xs">结案方式 *</Label>
                    <Select
                      value={closedReason}
                      onValueChange={(v) => setClosedReason(v as ArchiveClosedReason)}
                    >
                      <SelectTrigger className="h-9">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {(Object.keys(CLOSED_REASON_CN) as ArchiveClosedReason[]).map((k) => (
                          <SelectItem key={k} value={k}>
                            {CLOSED_REASON_CN[k]}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-1.5">
                    <Label className="text-xs">结案日期 *</Label>
                    <Input
                      type="date"
                      value={completedAt}
                      onChange={(e) => setCompletedAt(e.target.value)}
                      className="h-9"
                    />
                  </div>
                </div>
                <div className="space-y-1.5">
                  <Label className="text-xs">裁判结果摘要</Label>
                  <Textarea
                    value={judgmentSummary}
                    onChange={(e) => setJudgmentSummary(e.target.value)}
                    placeholder="如：一审判决支持原告诉请，对方未上诉，判决于 2026-04-15 生效"
                    rows={2}
                  />
                </div>
                <div className="space-y-1.5">
                  <div className="flex items-baseline justify-between">
                    <Label className="text-xs">结案小结 *</Label>
                    {summaryFromClose && (
                      <span className="inline-flex items-center gap-1 text-[10px] text-primary">
                        <Sparkles className="h-3 w-3" />
                        已引用结案时填写的小结，可直接编辑
                      </span>
                    )}
                  </div>
                  <Textarea
                    value={summary}
                    onChange={(e) => {
                      setSummary(e.target.value);
                      setSummaryFromClose(false);
                    }}
                    placeholder="案件办理过程概述、关键节点、得失复盘等"
                    rows={3}
                  />
                </div>
              </section>

              {/* 材料清单 */}
              {checklist && (
                <section className="space-y-2">
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-medium">{checklist.title}</h3>
                    <span className="text-xs text-muted-foreground">
                      勾选已完成材料；带 * 为必交
                    </span>
                  </div>
                  <div className="rounded-lg border border-border/60 divide-y divide-border/60">
                    {checklist.items.map((item) => (
                      <label
                        key={item.id}
                        className={`flex items-start gap-3 px-3 py-2.5 cursor-pointer hover:bg-muted/30 ${
                          item.autoGenerated ? "bg-[#9B7BF7]/5" : ""
                        }`}
                      >
                        <Checkbox
                          checked={!!checked[item.id]}
                          disabled={item.autoGenerated}
                          onCheckedChange={(v) =>
                            setChecked((prev) => ({ ...prev, [item.id]: !!v }))
                          }
                          className="mt-0.5"
                        />
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 text-sm">
                            <span>{item.label}</span>
                            {item.required && <span className="text-destructive">*</span>}
                            {item.autoGenerated && (
                              <span className="inline-flex items-center gap-1 text-[10px] text-[#9B7BF7]">
                                <Sparkles className="h-3 w-3" />
                                自动生成
                              </span>
                            )}
                          </div>
                          {item.hint && (
                            <p className="text-xs text-muted-foreground mt-0.5">{item.hint}</p>
                          )}
                        </div>
                      </label>
                    ))}
                  </div>
                </section>
              )}

              {/* 缺项警告 */}
              {missingRequired.length > 0 && (
                <Alert variant="destructive" className="border-amber-500/40 bg-amber-500/10 text-amber-200">
                  <AlertTriangle className="h-4 w-4" />
                  <AlertTitle className="text-sm">
                    仍有 {missingRequired.length} 项必交材料未勾选
                  </AlertTitle>
                  <AlertDescription className="text-xs mt-1">
                    {missingRequired.map((x) => x.label).join("、")}
                  </AlertDescription>
                  <label className="mt-3 flex items-center gap-2 cursor-pointer">
                    <Checkbox
                      checked={forceWithMissing}
                      onCheckedChange={(v) => setForceWithMissing(!!v)}
                    />
                    <span className="text-xs">强制归档（缺项 ID 会记入档案，可在归档详情查看）</span>
                  </label>
                </Alert>
              )}
            </div>
          </ScrollArea>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={isPending}>
            取消
          </Button>
          <Button
            onClick={handleSubmit}
            disabled={isPending || loading}
            className="bg-[#9B7BF7] text-white hover:bg-[#9B7BF7]/90"
          >
            {isPending && <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />}
            确认归档
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
